### ISSUE TITLE
error compiling vignette nlmixr_theo.Rmd when running devtools::build("xgxr-master")

### ISSUE THREAD

**Issue by margoal1** [Novartis/xgxr#1]
![image](https://user-images.githubusercontent.com/44787126/60824039-e6afbb00-a176-11e9-9051-2059a8a182b0.png)

**Comment by iamstein** [comment]
This issue was fixed in the master branch (I forgot to create/check-out an Andy branch).  But, "build" may still not work, but this time for other, weird Rmarkdowny reasons

```{r}

> > devtools::build()
✔  checking for file ‘/Users/steinanf/GitHub/xgxr/DESCRIPTION’ ...
─  preparing ‘xgxr’: (1s)
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (4.2s)
   
   Attaching package: 'dplyr'
   
   The following object is masked from 'package:gridExtra':
   
       combine
   
   The following objects are masked from 'package:stats':
   
       filter, lag
   
   The following objects are masked from 'package:base':
   
       intersect, setdiff, setequal, union
   
   pandoc: Could not fetch PK_Multiple_Ascending_Dose_files/figure-html/conc_vs_time_overview%20-1.png
   PK_Multiple_Ascending_Dose_files/figure-html/conc_vs_time_overview -1.png: openBinaryFile: does not exist (No such file or directory)
   Error: processing vignette 'PK_Multiple_Ascending_Dose.Rmd' failed with diagnostics:
   pandoc document conversion failed with error 67
   Execution halted
Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
```

**Comment by iamstein** [comment]
> devtools::build()
✔  checking for file ‘/Users/steinanf/GitHub/xgxr/DESCRIPTION’ ...
─  preparing ‘xgxr’: (1s)
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (4.2s)
   
   Attaching package: 'dplyr'
   
   The following object is masked from 'package:gridExtra':
   
       combine
   
   The following objects are masked from 'package:stats':
   
       filter, lag
   
   The following objects are masked from 'package:base':
   
       intersect, setdiff, setequal, union
   
   pandoc: Could not fetch PK_Multiple_Ascending_Dose_files/figure-html/conc_vs_time_overview%20-1.png
   PK_Multiple_Ascending_Dose_files/figure-html/conc_vs_time_overview -1.png: openBinaryFile: does not exist (No such file or directory)
   Error: processing vignette 'PK_Multiple_Ascending_Dose.Rmd' failed with diagnostics:
   pandoc document conversion failed with error 67
   Execution halted
Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error

**Comment by mattfidler** [comment]
Did you fix this?

**Comment by iamstein** [comment]
@mattfidler  I believe this was fixed back in July 8.

**Comment by mattfidler** [comment]
Thanks Andy
