### ISSUE TITLE
Log transform of negative numbers

### ISSUE THREAD

**Issue by anweshacsbmgh** [Novartis/xgxr#21]
Would it be possible to create a function within xgx to plot negative values with a log-scale? I have a quick and dirty solution, but it is kinda ugly. A neater solution would be helpful.

**Comment by iamstein** [comment]
Can you share your code together with a dummy dataset that does what you want?  I don’t understand this request because you can’t take the log of a negative number. An example would help us understand what a solution would look like.

**Comment by anweshacsbmgh** [comment]
Sure, I can email you an example. Essentially, I "transformed" the values so that all the values are >0, and then after plotting, I changed the ticks to read the "back-transformed" original value.

**Comment by iamstein** [comment]
It’s better to just paste the example here. The best practice for github issues is to put code illustrating the issue. I’ll have to think about if there’s an easy way to do what you describe. It involves changing the actual data so I think I’m some ways what you did is the most transparent and best option. And it sounds like your solution is only 2 lines of code, one to change the data and one to change the labels!  Do you think an xgx function would add a lot of value here for saving one line of code?

**Comment by anweshacsbmgh** [comment]
I have simplified my section of the code FYR. I think if there was a better way to pick those tick positions so that the ticks are relatively equally spaced, that might make the figure better.

- First, I identify the minimum value for each group:
df = df %>%
  dplyr::group_by(groupname) %>%
  dplyr::mutate(minVal = min(absolute_change,na.rm = TRUE))

- I defined where I'd like to put the ticks (totally arbitrary, and isn't the best choice)
break_point = list("A" = c(-25,-10,0,50,500,1000))  #say groupname is A

- Chose an arbitrary epsilon, to force the values to be greater than 0
  epsilon = sign(minVal) * minVal*0.3    #assuming this epsilon is 30% of the magnitude of minVal, if minVal is negative, sign(minVal) = -1

- Transforming the variable:
  dfTran = df %>%
    mutate(absolute_change_trans = absolute_change-minVal+epsilon) # transforming the absolute change, so all is positive

Plotting and reverse transforming the variable:
  p = ggplot(dfTran, 
               aes(x = TIME, y = absolute_change_trans, group = ID)) + 
    geom_line() + 
    geom_point() + 
    scale_y_continuous(trans = "log10",
                       breaks = break_point[["A"]]-minVal+epsilon,
                       labels = as.character(break_point[["A"]])) 
print(p)

**Comment by iamstein** [comment]
Anwesha, can you provide a complete code that I can run that will create the plot you want from a dataset that you also provide, either using an R built in dataset or one that you create with a few lines of code?  We would then take this code and run it to see what it does and then see about improving it or making a function.  A piece of code that runs and generates a representative graph is what we would need to use as a starting point to develop any tool and you are the best person to provide the starting point!

**Comment by iamstein** [comment]
I'm closing this issue because I think something like blq_trans from @billdenney is the right way to handle BLQ data.  I don't think negative numbers belong directly on log-transformed graph and I think the best there is to just use ggplot2 standard behavior for dealing log transformed negative numbers, so the user is aware there's an issue to resolve.
