### ISSUE TITLE
Refine `xgx_save` to give more information on error.

### ISSUE THREAD

**Issue by mattfidler** [Novartis/xgxr#34]
If `dirs` in `xgx_save` is not a list the error is not very readable:

```r
R 3.6.1> xgx_save(PC$pptWidth, PC$pptWidth, DIR$out, "bcva-vs-time", g=gg)
Error: $ operator is invalid for atomic vectors
```

**Expected behavior**
A better way to handle this is to make sure that `dirs` is a list.  If not, tell the user what the structure of this list should be.

This depends on the DaVinci `xgxr`

**Comment by iamstein** [comment]
Thanks @mattfidler.  We could introduce a check that it's a list.  But also, just curious, how did you use it, just as a string for the output directory?

**Comment by mattfidler** [comment]
I did;  I misread the comment on the xgxr website and that was my assumption.
