### ISSUE TITLE
xgxr pkgdown function reference?

### ISSUE THREAD

**Issue by yoshidk6** [Novartis/xgxr#38]
Thank you so much for making such an excellent package and it's associated xGx resource available!

If possible it would be helpful to have a function reference page built with pkgdown package, like nlmixr has: https://nlmixrdevelopment.github.io/nlmixr/reference/index.html
There is already a PDF function reference in CRAN, but html version is easier for navigation.

**Comment by iamstein** [comment]
Thanks for the idea @yoshidk6 and for implementing it @mattfidler.   The pkgdown page now exists here: http://opensource.nibr.com/xgxr/  

Let us know if it's helpful or if you have any feedback!

**Comment by yoshidk6** [comment]
Yes this is great, thank you very much!!
