### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by mattfidler** [Novartis/xgxr#39]
Automatic check and automatic pkgdown site creation. Related to #38

**Comment by mattfidler** [comment]
I accidently pushed this to the main branch in ac7b9de

**Comment by mattfidler** [comment]
The pkgdown needs to be turned on by the site administrator, I'm unsure if that is you @iamstein .  We can talk on Monday.

**Comment by mattfidler** [comment]
The checks are successful and the pkgdown site is built.  

The coverage isn't created;  the error report is 

```
Error in covr::coveralls() : 
  Failed to upload coverage data. Reply by Coveralls: Couldn't find a repository matching this job.
Execution halted
```

**Comment by iamstein** [comment]
Thanks @mattfidler for implementing this!
