### ISSUE TITLE
Feature request: support minutes in `xgx_scale_time_units_()`

### ISSUE THREAD

**Issue by billdenney** [Novartis/xgxr#63]
I needed a minutes x-axis for a current dataset, but `xgx_scale_time_units_()` only supports between hours and years.

1. Would a PR to add "min" and "minutes" to the `units_dataset` and `units_plot` options be considered?
2. Currently, if you give `units_dataset = "min"`, then it assumes that the units are "months" which is inaccurate.  I think that stricter input testing would be helpful to prevent unintentional unit assignment.

**Comment by iamstein** [comment]
minutes and seconds have now been added (though "min" won't work, requires full unit name now of year, month, week, day, hour, minute, second).  The only flexibility is in capitalization and in ending the unit with an "s" otherwise an error is thrown.

**Comment by billdenney** [comment]
Thanks!
