### ISSUE TITLE
devtools::check() issue

### ISSUE THREAD

**Issue by iamstein** [Novartis/xgxr#66]
devtools::check() - give this NOTE regarding the predict.nls.R function.

Found the following apparent S3 methods exported but not registered:
    predict.nls
  See section ‘Registering S3 methods’ in the ‘Writing R Extensions’
  manual.

**Comment by mattfidler** [comment]
Checks are now working for me on #67

**Comment by mattfidler** [comment]
I can go over this with you if you want/need.
