### ISSUE TITLE
Perhaps add flagging censoring columns like they do in Monolix?

### ISSUE THREAD

**Issue by mattfidler** [Novartis/xgxr#9]
I'm unsure if you read the monolix documentation, but I think that flagging censoring somehow may be useful for exploratory plots.

**Comment by mattfidler** [comment]
http://monolix.lixoft.com/data-and-models/censoreddata/

**Comment by iamstein** [comment]
Hey Matt, can you say more what you mean, here?  Is there a specific function that you are suggesting we change?  Or something in the vignettes?  In the xGx site, we do have a CENS column and in some plots, highlight this BLQ data. 
http://opensource.nibr.com/xgx/Single_Ascending_Dose_PK.html#concentration_over_time,_faceted_by_dose,_dots_and_lines_grouped_by_individual

**Comment by mattfidler** [comment]
Maybe make a `geom_cens` that does these for you? 

I was going to do something similar for `nlmixr` but haven't quite gotten to it.

**Comment by iamstein** [comment]
Hmm. I think that’s functionality I’d prefer not to implement. Because it’s so easy with ggplot already. Just set the shape equal to CENS. I tend not to like adding functions for doing things that are already easy with ggplot2. But then I guess how one defines easy is kind of arbitrary.

**Comment by mattfidler** [comment]
OK.
